//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHStudios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowplayerResource
    {
        public FlowplayerResource()
        {
            this.Games = new HashSet<Game>();
        }
    
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public string WebM { get; set; }
        public string MP4 { get; set; }
        public string Flash { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
    }
}
