//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHStudios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectFeature
    {
        public int Project_ID { get; set; }
        public int Feature_ID { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual Project Project { get; set; }
    }
}
