//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHStudios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Series
    {
        public Series()
        {
            this.SeriesResources = new HashSet<SeriesResource>();
            this.Videos = new HashSet<Video>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string YouTube_ID { get; set; }
        public bool Finished { get; set; }
        public bool Legacy { get; set; }
        public System.DateTime Created { get; set; }
        public string ShortName { get; set; }
    
        public virtual ICollection<SeriesResource> SeriesResources { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
