//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHStudios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoResource
    {
        public int Video_ID { get; set; }
        public int Resource_ID { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual Video Video { get; set; }
    }
}
